import Head from "next/head";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import SimplifyTeam from "../components/SimplifyTeam";
import Testimonial from "../components/Testimonial";
import WhatDifferent from "../components/WhatDifferent";

export default function Home() {
	return (
		<div className='bg-mobile xl:bg-desktop'>
			<Head>
				<title>Manage Landing Page</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Navbar />
			<Banner />
			<WhatDifferent />
			<Testimonial />
			<SimplifyTeam />
			<Footer />
		</div>
	);
}
